# .github/workflows/tauri-build.yml
name: Build desktop installers

on:
  # Executa quando o workflow de binários terminar (sucesso ou não).
  workflow_run:
    workflows: ["Build micro-service binaries (macOS-Linux-Windows)"]
    types: [completed]

jobs:
  tauri:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v4

      # ↓↓↓ 1) Baixa TODOS os artifacts gerados pelo workflow anterior
      - name: ⬇️  Download sidecar artifacts
        uses: actions/download-artifact@v4
        with:
          path: sidecars     # serão salvos em sidecars/**

      # ↓↓↓ 2) Move apenas os binários do SO atual p/ src-tauri/bin
      - name: 🚚  Move sidecars to src-tauri/bin
        run: |
          mkdir -p src-tauri/bin
          case "${{ runner.os }}" in
            macOS)
              mv sidecars/*-macos src-tauri/bin/
              chmod +x src-tauri/bin/*-macos
              ;;
            Linux)
              mv sidecars/*-ubuntu src-tauri/bin/
              chmod +x src-tauri/bin/*-ubuntu
              ;;
            Windows)
              mv sidecars\\*-windows.exe src-tauri\\bin\\
              ;;
          esac

      # ↓↓↓ 3) Build do front-end React/Next/etc.
      - name: ⚙️  Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: |
          npm ci
          npm run build

      # ↓↓↓ 4) Build & bundle Tauri
      - name: 🛠️  Build Tauri app
        uses: tauri-apps/tauri-action@v0.4
        with:
          args: >
            --target ${{ fromJSON('{
              "macos-latest":"universal-apple-darwin",
              "ubuntu-latest":"x86_64-unknown-linux-gnu",
              "windows-latest":"x86_64-pc-windows-msvc"
            }')[matrix.os] }}
        env:
          # (opcional) chaves para assinatura
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      # Os instaladores ficarão disponíveis em "Artifacts" deste job.
