name: Build installers and publish download site

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build installers (Windows, macOS, Linux)
    runs-on: ${{ matrix.os }}
    env:
      TAURI_SIGNING_REQUIRED: "false"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend deps
        run: npm ci

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux system deps (GTK/WebKit/GLib)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev
          sudo apt-get install -y \
            libgtk-3-dev libglib2.0-dev libayatana-appindicator3-dev \
            librsvg2-dev patchelf pkg-config build-essential

      - name: Build with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

      - name: Gather built artifacts for site (Unix)
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: |
          mkdir -p "site/public/downloads/${{ matrix.platform }}"
          find src-tauri/target -type f \( -name "*.dmg" -o -name "*.app.tar.gz" -o -name "*.msi" -o -name "*.exe" -o -name "*.deb" -o -name "*.AppImage" \) \
            -exec cp {} "site/public/downloads/${{ matrix.platform }}/" \; || true

      - name: Gather built artifacts for site (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "site/public/downloads/${{ matrix.platform }}" | Out-Null
          Get-ChildItem -Path "src-tauri/target" -Recurse -Include *.dmg,*.app.tar.gz,*.msi,*.exe,*.deb,*.AppImage -ErrorAction SilentlyContinue |
            ForEach-Object { Copy-Item $_.FullName "site/public/downloads/${{ matrix.platform }}" -Force }

      - name: Upload site artifacts (per-platform)
        uses: actions/upload-artifact@v4
        with:
          name: downloads-${{ matrix.platform }}
          path: site/public/downloads/${{ matrix.platform }}

  website:
    name: Publish download site (GitHub Pages)
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: pages
      cancel-in-progress: true
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: downloads-macos
          path: site/public/downloads/macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: downloads-windows
          path: site/public/downloads/windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: downloads-linux
          path: site/public/downloads/linux

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Place static site files
        shell: bash
        run: |
          mkdir -p site/public
          if [ -d site-src ]; then cp -R site-src/* site/public/; fi

          # cria índices simples nas pastas de downloads (sem heredoc)
          for os in windows macos linux; do
            dir="site/public/downloads/$os"
            mkdir -p "$dir"
            {
              echo '<!doctype html><meta charset="utf-8"><title>Downloads</title>'
              echo '<body style="font-family:system-ui;padding:24px"><h2>Downloads: '"$os"'</h2><ul>'
              for f in "$dir"/*; do
                [ -f "$f" ] || continue
                bn=$(basename "$f")
                echo '<li><a href="./'"$bn"'">'"$bn"'</a></li>'
              done
              echo '</ul><p><a href="../../index.html">&larr; Voltar</a></p></body>'
            } > "$dir/index.html"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
